name: Deploy
on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: "Install dependencies"
        run: npm ci --force
      - name: "Replace Angular.json with V16's one"
        run: npm run predeploy
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: >-
            ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TABLETOP_CHARACTER_SHEET_63388 }}
          channelId: live
          projectId: tabletop-character-sheet-63388
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
