name: Verify project integrity

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci --force
      - uses: actions/upload-artifact@master
        with:
          name: node-modules
          path: node_modules

  check:
    name: Check lint and format
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - uses: actions/download-artifact@master
        with:
          name: node-modules
          path: node_modules
      - run: npm run check:ci

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - uses: actions/download-artifact@master
        with:
          name: node-modules
          path: node_modules
      - run: npm run build

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - uses: actions/download-artifact@master
        with:
          name: node-modules
          path: node_modules
      - run: npm run test:ci
